const defaultProducts = [
  {
    id: 1,
    name: "Trà Đào Cam Sả (M)",
    price: 60000,
    category: "Thức uống và Bánh",
    img: "img/tradaocamsa.png",
    stock: 50,
    desc: "Trà đào ngọt thanh, sả thơm lừng.",
  },
  {
    id: 2,
    name: "Trà Đào Cam Sả (L)",
    price: 60000,
    category: "Thức uống và Bánh",
    img: "img/tradaocamsa.png",
    stock: 50,
    desc: "Trà đào ngọt thanh, sả thơm lừng.",
  },
  {
    id: 3,
    name: "Trà Sữa Ô Long (M)",
    price: 60000,
    category: "Thức uống và Bánh",
    img: "img/trasuaolong.png",
    stock: 40,
    desc: "Trà Ô Long hảo hạng.",
  },
  {
    id: 4,
    name: "Trà Sữa Ô Long (L)",
    price: 60000,
    category: "Thức uống và Bánh",
    img: "img/trasuaolong.png",
    stock: 40,
    desc: "Trà Ô Long hảo hạng.",
  },
  {
    id: 5,
    name: "Hồng Trà Sữa (M)",
    price: 60000,
    category: "Thức uống và Bánh",
    img: "img/hongtrasua.png",
    stock: 30,
    desc: "Hồng trà nguyên bản.",
  },
  {
    id: 6,
    name: "Hồng Trà Sữa (L)",
    price: 60000,
    category: "Thức uống và Bánh",
    img: "img/hongtrasua.png",
    stock: 30,
    desc: "Hồng trà nguyên bản.",
  },
  {
    id: 7,
    name: "Trà Sữa Lài (M)",
    price: 55000,
    category: "Thức uống và Bánh",
    img: "img/trasualai.png",
    stock: 20,
    desc: "Hương lài thơm ngát.",
  },
  {
    id: 8,
    name: "Trà Sữa Lài (L)",
    price: 55000,
    category: "Thức uống và Bánh",
    img: "img/trasualai.png",
    stock: 20,
    desc: "Hương lài thơm ngát.",
  },

  // ĐÁ XAY
  {
    id: 9,
    name: "Matcha Đá Xay (M)",
    price: 55000,
    category: "Thức uống và Bánh",
    img: "img/matcha.png",
    stock: 50,
    desc: "Đá xay mát lạnh.",
  },
  {
    id: 10,
    name: "Matcha Đá Xay (L)",
    price: 65000,
    category: "Thức uống và Bánh",
    img: "img/matcha.png",
    stock: 50,
    desc: "Đá xay mát lạnh.",
  },
  {
    id: 11,
    name: "Choco Đá Xay (M)",
    price: 50000,
    category: "Thức uống và Bánh",
    img: "img/choco.png",
    stock: 50,
    desc: "Sô cô la đậm đà.",
  },
  {
    id: 12,
    name: "Choco Đá Xay (L)",
    price: 60000,
    category: "Thức uống và Bánh",
    img: "img/choco.png",
    stock: 50,
    desc: "Sô cô la đậm đà.",
  },
  {
    id: 13,
    name: "Cookie Đá Xay (M)",
    price: 50000,
    category: "Thức uống và Bánh",
    img: "img/cookie.png",
    stock: 50,
    desc: "Bánh quy xay giòn rụm.",
  },
  {
    id: 14,
    name: "Cookie Đá Xay (L)",
    price: 60000,
    category: "Thức uống và Bánh",
    img: "img/cookie.png",
    stock: 50,
    desc: "Bánh quy xay giòn rụm.",
  },

  // SỮA TƯƠI
  {
    id: 15,
    name: "Sữa Tươi Trân Châu (M)",
    price: 45000,
    category: "Thức uống và Bánh",
    img: "img/sttc.png",
    stock: 50,
    desc: "Sữa tươi ngọt ngào.",
  },
  {
    id: 16,
    name: "Sữa Tươi Trân Châu (L)",
    price: 55000,
    category: "Thức uống và Bánh",
    img: "img/sttc.png",
    stock: 50,
    desc: "Sữa tươi ngọt ngào.",
  },
  {
    id: 17,
    name: "Sữa Dâu Latte (M)",
    price: 42000,
    category: "Thức uống và Bánh",
    img: "img/suadau.png",
    stock: 50,
    desc: "Hương dâu tự nhiên.",
  },
  {
    id: 18,
    name: "Sữa Dâu Latte (L)",
    price: 52000,
    category: "Thức uống và Bánh",
    img: "img/suadau.png",
    stock: 50,
    desc: "Hương dâu tự nhiên.",
  },
  {
    id: 19,
    name: "Sữa Tươi Việt Quất TC (M)",
    price: 55000,
    category: "Thức uống và Bánh",
    img: "img/vietquat.png",
    stock: 50,
    desc: "Việt quất chua ngọt.",
  },
  {
    id: 20,
    name: "Sữa Tươi Việt Quất TC (L)",
    price: 65000,
    category: "Thức uống và Bánh",
    img: "img/vietquat.png",
    stock: 50,
    desc: "Việt quất chua ngọt.",
  },

  // TRÀ
  {
    id: 21,
    name: "Trà Ổi Hồng (M)",
    price: 55000,
    category: "Thức uống và Bánh",
    img: "img/traoi.png",
    stock: 50,
    desc: "Thanh mát vị ổi.",
  },
  {
    id: 22,
    name: "Trà Ổi Hồng (L)",
    price: 65000,
    category: "Thức uống và Bánh",
    img: "img/traoi.png",
    stock: 50,
    desc: "Thanh mát vị ổi.",
  },
  {
    id: 23,
    name: "Trà Vải (M)",
    price: 55000,
    category: "Thức uống và Bánh",
    img: "img/travai.png",
    stock: 50,
    desc: "Vải ngâm ngọt lịm.",
  },
  {
    id: 24,
    name: "Trà Vải (L)",
    price: 65000,
    category: "Thức uống và Bánh",
    img: "img/travai.png",
    stock: 50,
    desc: "Vải ngâm ngọt lịm.",
  },
  {
    id: 25,
    name: "Trà Dâu (M)",
    price: 60000,
    category: "Thức uống và Bánh",
    img: "img/tradau.png",
    stock: 50,
    desc: "Trà dâu tươi mát.",
  },
  {
    id: 26,
    name: "Trà Dâu (L)",
    price: 70000,
    category: "Thức uống và Bánh",
    img: "img/tradau.png",
    stock: 50,
    desc: "Trà dâu tươi mát.",
  },
  {
    id: 27,
    name: "Trà Thạch Đào (M)",
    price: 65000,
    category: "Thức uống và Bánh",
    img: "img/trathachdao.png",
    stock: 50,
    desc: "Kèm thạch đào giòn.",
  },
  {
    id: 28,
    name: "Trà Thạch Đào (L)",
    price: 75000,
    category: "Thức uống và Bánh",
    img: "img/trathachdao.png",
    stock: 50,
    desc: "Kèm thạch đào giòn.",
  },

  // CÀ PHÊ
  {
    id: 29,
    name: "Tiramisu Coffee (M)",
    price: 59000,
    category: "Thức uống và Bánh",
    img: "img/tiramisucf.png",
    stock: 50,
    desc: "Vị bánh Tiramisu.",
  },
  {
    id: 30,
    name: "Tiramisu Coffee (L)",
    price: 69000,
    category: "Thức uống và Bánh",
    img: "img/tiramisucf.png",
    stock: 50,
    desc: "Vị bánh Tiramisu.",
  },
  {
    id: 31,
    name: "Mocha (M)",
    price: 55000,
    category: "Thức uống và Bánh",
    img: "img/mocha.png",
    stock: 50,
    desc: "Cà phê pha sô cô la.",
  },
  {
    id: 32,
    name: "Mocha (L)",
    price: 65000,
    category: "Thức uống và Bánh",
    img: "img/mocha.png",
    stock: 50,
    desc: "Cà phê pha sô cô la.",
  },
  {
    id: 33,
    name: "Cà Phê Pha Phin (M)",
    price: 39000,
    category: "Thức uống và Bánh",
    img: "img/caphephin.png",
    stock: 50,
    desc: "Cà phê truyền thống.",
  },
  {
    id: 34,
    name: "Cà Phê Pha Phin (L)",
    price: 49000,
    category: "Thức uống và Bánh",
    img: "img/caphephin.png",
    stock: 50,
    desc: "Cà phê truyền thống.",
  },
  {
    id: 35,
    name: "Latte Đá (M)",
    price: 55000,
    category: "Thức uống và Bánh",
    img: "img/latteda.png",
    stock: 50,
    desc: "Nhiều sữa béo ngậy.",
  },
  {
    id: 36,
    name: "Latte Đá (L)",
    price: 65000,
    category: "Thức uống và Bánh",
    img: "img/latteda.png",
    stock: 50,
    desc: "Nhiều sữa béo ngậy.",
  },
  {
    id: 37,
    name: "Latte Nóng (M)",
    price: 55000,
    category: "Thức uống và Bánh",
    img: "img/latte.png",
    stock: 50,
    desc: "Nhiều sữa béo ngậy.",
  },
  {
    id: 38,
    name: "Latte Nóng (L)",
    price: 65000,
    category: "Thức uống và Bánh",
    img: "img/latte.png",
    stock: 50,
    desc: "Nhiều sữa béo ngậy.",
  },
  {
    id: 39,
    name: "Cold Brew (M)",
    price: 50000,
    category: "Thức uống và Bánh",
    img: "img/coldbrew.png",
    stock: 50,
    desc: "Cà phê ủ lạnh.",
  },
  {
    id: 40,
    name: "Cold Brew (L)",
    price: 60000,
    category: "Thức uống và Bánh",
    img: "img/coldbrew.png",
    stock: 50,
    desc: "Cà phê ủ lạnh.",
  },

  // BÁNH NGỌT (1 Size)
  {
    id: 41,
    name: "Bánh Tiramisu",
    price: 50000,
    category: "Thức uống và Bánh",
    img: "img/tiramisu.png",
    stock: 20,
    desc: "Bánh mềm tan trong miệng.",
  },
  {
    id: 42,
    name: "Passion Cake",
    price: 45000,
    category: "Thức uống và Bánh",
    img: "img/passioncake.png",
    stock: 20,
    desc: "Bánh chanh dây chua ngọt.",
  },
  {
    id: 43,
    name: "Croissant",
    price: 35000,
    category: "Thức uống và Bánh",
    img: "img/croissant.png",
    stock: 20,
    desc: "Bánh sừng bò ngàn lớp.",
  },
  {
    id: 44,
    name: "Red Velvet Cake",
    price: 45000,
    category: "Thức uống và Bánh",
    img: "img/redcake.png",
    stock: 20,
    desc: "Bánh đỏ nhung cao cấp.",
  },
  {
    id: 45,
    name: "Bánh Macaron (2 cái)",
    price: 35000,
    category: "Thức uống và Bánh",
    img: "img/macaron.png",
    stock: 20,
    desc: "Bánh Pháp ngọt ngào.",
  },

  // SẢN PHẨM ĐÓNG GÓI
  {
    id: 46,
    name: "Cà Phê Đóng Gói (250g)",
    price: 90000,
    category: "Sản phẩm đóng gói",
    img: "img/caphegoi.png",
    stock: 100,
    desc: "Hạt cà phê rang xay.",
  },
  {
    id: 47,
    name: "Cà Phê Đóng Gói (500g)",
    price: 170000,
    category: "Sản phẩm đóng gói",
    img: "img/caphegoi.png",
    stock: 100,
    desc: "Hạt cà phê rang xay.",
  },
  {
    id: 48,
    name: "Trà Đóng Gói (100g)",
    price: 85000,
    category: "Sản phẩm đóng gói",
    img: "img/tradonggoi.png",
    stock: 100,
    desc: "Lá trà sấy khô.",
  },
  {
    id: 49,
    name: "Trà Đóng Gói (250g)",
    price: 160000,
    category: "Sản phẩm đóng gói",
    img: "img/tradonggoi.png",
    stock: 100,
    desc: "Lá trà sấy khô.",
  },
  {
    id: 50,
    name: "Trà Tắc Đóng Gói (250g)",
    price: 75000,
    category: "Sản phẩm đóng gói",
    img: "img/tratac.png",
    stock: 100,
    desc: "Trà hòa tan tiện lợi.",
  },
  {
    id: 51,
    name: "Trà Tắc Đóng Gói (500g)",
    price: 140000,
    category: "Sản phẩm đóng gói",
    img: "img/tratac.png",
    stock: 100,
    desc: "Trà hòa tan tiện lợi.",
  },
    {
    id: 52,
    name: "Cà Phê Rang Xay (250g)",
    price: 90000,
    category: "Sản phẩm đóng gói",
    img: "img/caphe250g.png",
    stock: 100,
    desc: "Cà phê rang xay với hương vị đậm đà.",
  },
    {
    id: 53,
    name: "Cà Phê Rang Xay (500g)",
    price: 170000,
    category: "Sản phẩm đóng gói",
    img: "img/capherang.png",
    stock: 100,
    desc: "Cà phê rang xay với hương vị đậm đà.",
  },
    {
    id: 54,
    name: "Combo cà phê hòa tan",
    price: 160000,
    category: "Sản phẩm đóng gói",
    img: "img/combo.png",
    stock: 100,
    desc: "Cà phê hòa tan tiện lợi.",
  },
];

// 1. Kiểm tra và cập nhật products
let savedProducts = JSON.parse(localStorage.getItem("products")) || [];

let isUpdated = false;
defaultProducts.forEach(defP => {
    let exists = savedProducts.find(p => p.id === defP.id);
    if (!exists) {
        savedProducts.push(defP);
        isUpdated = true;
    }
});

// Cập nhật lại category nếu thiếu (cho các món cũ hoặc món mới import)
savedProducts = savedProducts.map(p => {
    if (!p.category) {
        p.category = (p.id >= 46) ? "Sản phẩm đóng gói" : "Thức uống và Bánh";
        isUpdated = true;
    }
    return p;
});

if (isUpdated) {
    localStorage.setItem("products", JSON.stringify(savedProducts));
}

// 2. Khởi tạo các bảng khác nếu chưa có
if (!localStorage.getItem("users")) localStorage.setItem("users", JSON.stringify([]));
if (!localStorage.getItem("orders")) localStorage.setItem("orders", JSON.stringify([]));
if (!localStorage.getItem("contacts")) localStorage.setItem("contacts", JSON.stringify([]));